name = "Soulcyclone - Server Pack"
author = "Treeways"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "27309c833964690aa882b6c686a5e92b57a1b207633a1cf0c89b3b3588f2c828"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
