name = "Soulcyclone - Server Pack"
author = "Treeways"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "89e74024faa0a3a6f27b811646dae490cb4b79f813fb481c6bf5903a133a8c78"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
